micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempt: 10
  channels:
    keyManager:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempt: 10
#  server:
#    health:
#      enabled: true


jackson:
  serialization:
    writeDatesAsTimestamps: false